import Foundation

enum LocalizationStrings {
    static func resolvedLanguage(_ preference: AppLanguage) -> AppLanguage {
        switch preference {
        case .system:
            let preferred = Locale.preferredLanguages.first?.lowercased() ?? ""
            return preferred.hasPrefix("zh") ? .zhHans : .english
        case .zhHans, .english:
            return preference
        }
    }

    static func locale(for preference: AppLanguage) -> Locale {
        switch resolvedLanguage(preference) {
        case .zhHans:
            return Locale(identifier: "zh-Hans")
        case .english:
            return Locale(identifier: "en")
        case .system:
            return .current
        }
    }

    static func text(_ key: String, language preference: AppLanguage) -> String {
        let language = resolvedLanguage(preference)
        switch language {
        case .zhHans:
            return zhHans[key] ?? english[key] ?? key
        case .english:
            return english[key] ?? zhHans[key] ?? key
        case .system:
            return zhHans[key] ?? english[key] ?? key
        }
    }

    private static let zhHans: [String: String] = [
        "app.taskMenu": "任务",
        "app.reportMenu": "报告",
        "app.viewMenu": "视图",
        "app.reviewMenu": "复核",
        "systemMenu.file": "文件",
        "systemMenu.edit": "编辑",
        "systemMenu.view": "显示",
        "systemMenu.window": "窗口",
        "systemMenu.help": "帮助",
        "command.showWorkspace": "显示工作台",
        "command.startAudit": "开始审计",
        "command.cancelAudit": "取消审计",
        "command.reloadData": "重新加载数据",
        "command.toggleInspector": "显示或隐藏检查器",
        "command.openReports": "打开报告中心",
        "command.openLatestReport": "打开最近报告",
        "command.showLatestInFinder": "在 Finder 显示最近报告",
        "command.exportPDF": "导出当前报告 PDF",
        "command.exportHTML": "导出当前报告 HTML",
        "command.deleteReport": "删除当前报告记录",
        "toolbar.reload": "重新加载",
        "toolbar.start": "开始",
        "toolbar.cancel": "取消",
        "toolbar.settings": "设置",
        "toolbar.showInspector": "显示 Inspector",
        "toolbar.hideInspector": "隐藏 Inspector",
        "toolbar.toggleSidebar": "显示或隐藏侧边栏",
        "toolbar.newScan": "新建扫描任务",
        "toolbar.hideSearch": "收起搜索",
        "toolbar.titleMode.standard": "PitcherPlant",
        "toolbar.titleSelector": "扫描模式",
        "update.button.title": "更新",
        "update.button.help": "发现新版本",
        "update.button.accessibility": "发现新版本，查看更新",
        "toolbar.mode.auto": "自动",
        "toolbar.mode.auto.subtitle": "自动决定扫描策略",
        "toolbar.mode.deep": "深度",
        "toolbar.mode.deep.subtitle": "覆盖更多证据类型",
        "toolbar.mode.standard": "标准",
        "toolbar.mode.standard.subtitle": "当前默认扫描配置",
        "toolbar.mode.quick": "快速",
        "toolbar.mode.quick.subtitle": "优先速度与基础检查",
        "toolbar.mode.templates": "扫描模板",
        "toolbar.mode.template.default": "默认模板",
        "toolbar.mode.template.default.subtitle": "完整审计与报告输出",
        "toolbar.mode.template.review": "证据复核",
        "toolbar.mode.template.review.subtitle": "优先人工复核字段",
        "toolbar.mode.template.fast": "快速筛查",
        "toolbar.mode.template.fast.subtitle": "保留关键风险检查",
        "toolbar.mode.temporary": "临时扫描",
        "sidebar.categories": "工作导航",
        "sidebar.evidenceCollections": "证据集合",
        "sidebar.evidenceTypes": "证据类型",
        "sidebar.libraries": "资源管理",
        "sidebar.workspace": "工作台",
        "sidebar.allEvidence": "全部证据",
        "sidebar.favorites": "收藏",
        "sidebar.watched": "关注",
        "sidebar.newAudit": "新建审计",
        "sidebar.history": "历史任务",
        "sidebar.reports": "报告中心",
        "sidebar.textEvidence": "文本",
        "sidebar.codeEvidence": "代码",
        "sidebar.imageEvidence": "图片",
        "sidebar.metadataEvidence": "元数据",
        "sidebar.dedupEvidence": "重复",
        "sidebar.crossBatchEvidence": "跨批次",
        "sidebar.fingerprints": "指纹库",
        "sidebar.whitelist": "白名单",
        "sidebar.settings": "设置",
        "status.audits": "审计",
        "status.reports": "报告",
        "status.fingerprints": "指纹",
        "status.auditing": "审计中...",
        "status.latest": "最近",
        "status.ready": "就绪",
        "status.queued": "排队中",
        "status.running": "运行中",
        "status.succeeded": "已完成",
        "status.failed": "失败",
        "notice.auditCancelled": "审计已取消",
        "notice.auditFailed": "审计失败",
        "notice.bootstrapFailed": "启动初始化失败",
        "notice.reloadFailed": "数据刷新失败",
        "notice.deleteReportFailed": "删除报告失败",
        "notice.whitelistSaveFailed": "保存白名单失败",
        "notice.whitelistDeleteFailed": "删除白名单失败",
        "notice.exportFailed": "导出失败",
        "notice.exportRecordFailed": "导出记录写入失败",
        "notice.exportSucceeded": "导出完成",
        "notice.reviewSaveFailed": "保存复核失败",
        "notice.importSucceeded": "导入完成",
        "notice.importFailed": "导入失败",
        "notice.retryFailed": "重试失败",
        "notice.fingerprintImportSucceeded": "指纹导入完成",
        "notice.fingerprintImportSucceededMessage": "导入 %d 条指纹",
        "notice.fingerprintImportSucceededWithSkippedMessage": "导入 %d 条指纹，跳过 %d 条无效记录",
        "notice.fingerprintImportFailed": "指纹导入失败",
        "notice.fingerprintExportSucceeded": "指纹导出完成",
        "notice.fingerprintExportFailed": "指纹导出失败",
        "notice.fingerprintCleanupSucceeded": "指纹清理完成",
        "notice.fingerprintCleanupSucceededMessage": "清理 %d 条指纹",
        "notice.fingerprintCleanupFailed": "指纹清理失败",
        "notice.importQueuedSubmissionsMessage": "%d 个提交已入队",
        "audit.failure.cancelled": "审计已取消。",
        "audit.summary.base": "完成：%d 个文档 / %d 张图片 / %d 条历史指纹，耗时 %@ 秒",
        "audit.summary.recall": "%@；候选召回 %d/%d 对，耗时 %@ms",
        "stage.queued": "等待开始",
        "stage.initialize": "初始化",
        "stage.scan": "扫描文件",
        "stage.parse": "解析文档",
        "stage.parsed": "解析文档完成",
        "stage.ocrImages": "OCR / 图片提取",
        "stage.features": "生成特征",
        "stage.recall": "候选召回",
        "stage.text": "文本分析完成",
        "stage.code": "代码分析完成",
        "stage.image": "图片分析完成",
        "stage.metadata": "元数据分析完成",
        "stage.crossBatch": "跨批次匹配",
        "stage.aggregate": "风险聚合",
        "stage.export": "报告导出",
        "stage.done": "报告生成完成",
        "workspace.title": "工作台",
        "workspace.recentJobs": "最近任务",
        "workspace.recentReports": "最近报告",
        "workspace.reportCenter": "报告中心",
        "workspace.summary.jobs": "历史任务",
        "workspace.summary.reports": "报告",
        "workspace.summary.fingerprints": "指纹",
        "workspace.summary.whitelist": "白名单",
        "audit.title": "新建审计",
        "audit.subtitle": "配置目录、阈值、OCR 和白名单策略",
        "audit.running": "运行中",
        "audit.paths": "路径",
        "audit.paths.subtitle": "输入审计目录和报告输出位置",
        "audit.directory": "审计目录",
        "audit.outputDirectory": "报告目录",
        "audit.fileNameTemplate": "文件名模板",
        "audit.parameters": "检测参数",
        "audit.parameters.subtitle": "控制相似度、复用和跨批次阈值",
        "audit.textThreshold": "文本阈值",
        "audit.dedupThreshold": "重复阈值",
        "audit.imageThreshold": "图片阈值",
        "audit.simhashThreshold": "SimHash 位差",
        "audit.visionOCR": "Vision OCR",
        "audit.whitelistMode": "白名单模式",
        "audit.preset": "参数预设",
        "audit.preset.subtitle": "保存常用目录和阈值组合",
        "audit.presetName": "预设名称",
        "audit.saveCurrent": "保存当前",
        "audit.emptyPreset": "保存一套常用参数后，可在这里直接套用或运行。",
        "audit.applyPreset": "套用",
        "audit.runPreset": "运行",
        "audit.batchImport": "批量提交包导入",
        "audit.batchImport.subtitle": "支持 ZIP、嵌套目录和队伍目录识别",
        "audit.batchImport.description": "导入竞赛提交包后会自动生成待执行审计任务。",
        "audit.importSubmissions": "导入提交包",
        "mode.mark": "标记",
        "mode.hide": "隐藏",
        "history.searchPrompt": "搜索任务、路径、状态",
        "fingerprints.searchPrompt": "搜索文件、作者、SimHash",
        "fingerprints.importPackage": "导入指纹包",
        "fingerprints.exportPackage": "导出指纹包",
        "fingerprints.cleanupTag": "输入标签",
        "fingerprints.cleanup": "清理标签",
        "fingerprints.context": "批次 / 队伍",
        "fingerprints.tags": "标签",
        "fingerprints.importTagsPrompt": "导入标签，逗号分隔",
        "fingerprints.exportTagsPrompt": "导出包标签，逗号分隔",
        "fingerprints.matchCount": "%d 条命中",
        "fingerprints.cleanupConfirmTitle": "确认清理指纹标签",
        "fingerprints.cleanupConfirmMessage": "标签 %@ 当前命中 %d 条指纹。清理后会从本地指纹库移除这些记录。",
        "fingerprints.empty": "指纹库为空",
        "whitelist.searchPrompt": "搜索规则",
        "whitelist.type": "类型",
        "whitelist.newRule": "新增规则",
        "whitelist.rule": "规则",
        "whitelist.save": "保存",
        "whitelist.suggestions": "白名单建议",
        "whitelist.suggestions.failed": "建议生成失败：%@",
        "whitelist.noMatchedSuggestions": "暂无匹配建议",
        "whitelist.noMatchedSuggestionsDescription": "刷新建议后可接受或忽略候选规则",
        "whitelist.existingRules": "现有规则",
        "whitelist.noMatchedRules": "暂无匹配规则",
        "whitelist.noMatchedRulesDescription": "可在上方输入规则并保存",
        "whitelist.suggestionStatus": "建议状态",
        "whitelist.suggestionStatus.pending": "待处理",
        "whitelist.suggestionStatus.accepted": "已接受",
        "whitelist.suggestionStatus.dismissed": "已忽略",
        "whitelist.reason.textTemplate": "多份 WriteUP 反复出现，适合作为公共题面或模板片段",
        "whitelist.reason.codeTemplate": "结构化代码模板重复出现",
        "whitelist.reason.imageHash": "图片 hash 高频重复，可能是官方截图或公共素材",
        "whitelist.reason.metadata": "元数据在多份文件中出现，适合降权处理",
        "whitelist.reason.pathPattern": "路径目录名重复出现，适合做导入忽略或降权规则",
        "whitelist.generating": "生成中",
        "whitelist.refreshSuggestions": "刷新建议",
        "whitelist.acceptPending": "批量接受",
        "whitelist.pendingCount": "%d 条待处理",
        "whitelist.author": "作者",
        "whitelist.filename": "文件名",
        "whitelist.textSnippet": "文本片段",
        "whitelist.codeTemplate": "代码模板",
        "whitelist.imageHash": "图片 Hash",
        "whitelist.metadata": "元数据",
        "whitelist.pathPattern": "路径规则",
        "job.restoreParameters": "恢复参数",
        "job.runQueue": "运行队列",
        "job.retry": "重试任务",
        "job.timeline": "执行时间线",
        "job.stage": "阶段",
        "job.failures": "失败",
        "job.failedFiles": "失败文件",
        "job.copyDiagnostics": "复制错误诊断",
        "job.noSelection": "未选择任务",
        "job.noSelectionDescription": "在历史任务中选择一项后查看详情。",
        "common.countSuffix": "条",
        "common.none": "暂无",
        "common.open": "打开",
        "common.refresh": "刷新",
        "common.new": "新建",
        "common.import": "导入",
        "common.quit": "退出",
        "common.finder": "Finder",
        "common.delete": "删除",
        "common.export": "导出",
        "common.cancel": "取消",
        "common.search": "搜索",
        "common.file": "文件",
        "common.progress": "进度",
        "common.status": "状态",
        "common.actions": "操作",
        "common.count": "次数",
        "common.times": "%d 次",
        "common.itemCount": "%d 条",
        "common.unlabeled": "未标注",
        "common.samples": "样本",
        "common.seconds": "秒",
        "common.score": "分数",
        "common.type": "类型",
        "common.badge": "标记",
        "common.source": "来源",
        "common.summary": "摘要",
        "common.createdAt": "创建时间",
        "common.updatedAt": "更新时间",
        "common.path": "路径",
        "common.enabled": "开启",
        "common.disabled": "关闭",
        "common.followSystem": "跟随系统",
        "common.light": "浅色",
        "common.dark": "深色",
        "settings.title": "设置",
        "settings.searchPrompt": "搜索设置",
        "settings.general": "通用",
        "settings.appearance": "外观",
        "settings.auditDefaults": "审计默认值",
        "settings.reports": "报告",
        "settings.data": "数据",
        "settings.shortcuts": "快捷操作",
        "settings.language": "语言",
        "settings.languageDescription": "跟随系统或手动指定界面语言",
        "settings.menuBar": "菜单栏面板",
        "settings.menuBarDescription": "在菜单栏快速搜索审计和报告",
        "settings.workspace": "工作区路径",
        "settings.workspaceDescription": "当前项目和数据解析的根路径",
        "settings.theme": "外观模式",
        "settings.themeDescription": "跟随系统、浅色、深色三种外观模式",
        "settings.inspectorDefault": "业务页面默认显示详情栏",
        "settings.inspectorDefaultDescription": "用于审计、历史、报告和证据页面",
        "settings.compactRows": "紧凑列表密度",
        "settings.compactRowsDescription": "历史、报告和资料库页面使用更紧凑的行高",
        "settings.auditDirectoryDescription": "默认扫描 WriteUP 文档的目录",
        "settings.reportDirectoryDescription": "默认保存报告和导出文件的位置",
        "settings.fileNameTemplateDescription": "生成报告文件名时使用的模板",
        "settings.textThresholdDescription": "文本相似度命中阈值",
        "settings.dedupThresholdDescription": "重复内容检测阈值",
        "settings.imageThresholdDescription": "图片复用哈希距离阈值",
        "settings.simhashThresholdDescription": "跨批次 SimHash 允许位差",
        "settings.visionOCRDescription": "使用系统 Vision 识别 PDF 和图片文字",
        "settings.whitelistModeDescription": "白名单命中后标记或隐藏对应结果",
        "settings.calibration": "校准",
        "settings.calibrationPreset": "阈值预设",
        "settings.calibrationEvaluation": "校准评估",
        "settings.applyPreset": "应用预设",
        "settings.runCalibration": "运行校准",
        "settings.calibrationStatus": "校准状态",
        "settings.calibrationSummary": "样本 %d · Precision %.2f · Recall %.2f · F1 %.2f",
        "settings.calibrationDescription": "基于校准 fixture 展示 Precision、Recall 和 F1",
        "settings.calibrationMissingManifest": "未找到校准清单：Resources/Calibration/manifest.json",
        "settings.calibrationThreshold": "阈值",
        "settings.calibrationRowAccessibility": "%@，样本 %d，Precision %@，Recall %@，F1 %@",
        "settings.auditAssistant": "审计助手",
        "settings.auditAssistantMode": "助手模式",
        "settings.auditAssistantModeDescription": "选择关闭、本地命令或外部 API",
        "settings.auditAssistantTimeout": "超时时间",
        "settings.auditAssistantTimeoutDescription": "本地命令和外部 API 的最大等待秒数",
        "settings.auditAssistantKeychain": "Keychain 引用",
        "settings.auditAssistantKeychainDescription": "外部 API 凭据引用，将作为 X-PitcherPlant-Credential-Ref 请求头传递",
        "settings.auditAssistantEndpointCommand": "Endpoint / Command",
        "settings.auditAssistantLocalCommand": "本地命令",
        "settings.auditAssistantAPIEndpoint": "API Endpoint",
        "settings.auditAssistantDisabledSubtitle": "配置会保留，启用模式后生效",
        "settings.auditAssistantLocalSubtitle": "通过 zsh -lc 执行，证据 payload 会写入标准输入",
        "settings.auditAssistantAPISubtitle": "以 POST JSON 请求发送证据 payload",
        "calibration.preset.conservative": "保守",
        "calibration.preset.conservative.subtitle": "提高阈值，优先降低误报",
        "calibration.preset.balanced": "均衡",
        "calibration.preset.balanced.subtitle": "使用当前默认阈值",
        "calibration.preset.aggressive": "激进",
        "calibration.preset.aggressive.subtitle": "降低文本阈值，提高可疑召回",
        "auditAssistant.mode.disabled": "关闭",
        "auditAssistant.mode.localCommand": "本地命令",
        "auditAssistant.mode.externalAPI": "外部 API",
        "settings.preferInAppReports": "默认打开 App 内报告中心",
        "settings.preferInAppReportsDescription": "优先在 App 内查看审计结果",
        "settings.defaultExportFormat": "默认导出格式",
        "settings.defaultExportFormatDescription": "导出当前报告时使用的默认格式",
        "settings.attachmentPreview": "证据附件预览",
        "settings.attachmentPreviewDescription": "在报告详情中显示缩略图和附件预览",
        "settings.databaseLocation": "数据库位置",
        "settings.databaseLocationDescription": "当前 SQLite 数据库文件路径",
        "settings.recordCounts": "数据统计",
        "settings.recordCountsDescription": "当前数据库中的主要记录数量",
        "settings.openDataDirectory": "打开数据目录",
        "settings.reloadData": "重新加载数据",
        "settings.dataActionsDescription": "打开数据库目录或刷新当前数据",
        "settings.openReports": "打开报告中心",
        "settings.openReportsDescription": "切换到 App 内报告中心查看审计结果",
        "settings.exportHTML": "导出 HTML",
        "settings.exportPDF": "导出 PDF",
        "settings.exportReport": "导出报告",
        "settings.exportBundle": "证据包 ZIP",
        "settings.openFinder": "打开 Finder",
        "settings.choose": "选择",
        "settings.currentPrefix": "当前：",
        "settings.dataActions": "数据操作",
        "settings.quickOpen": "快速入口",
        "settings.reportActions": "报告操作",
        "settings.reportActionsDescription": "对当前选中的报告执行导出和定位操作",
        "settings.startAuditDescription": "使用当前审计默认值启动一次扫描",
        "reports.title": "报告中心",
        "reports.subtitle": "在 App 内查看章节、证据表格和详情",
        "reports.selectReport": "选择报告",
        "reports.filter": "筛选",
        "reports.evidenceFilter.all": "全部",
        "reports.evidenceFilter.highRisk": "高危",
        "reports.evidenceFilter.attachments": "带附件",
        "reports.sort": "排序",
        "reports.sort.default": "默认顺序",
        "reports.sort.severity": "风险优先",
        "reports.sort.title": "按标题",
        "evidence.addFavorite": "收藏证据",
        "evidence.removeFavorite": "取消收藏",
        "evidence.addWatch": "关注证据",
        "evidence.removeWatch": "取消关注",
        "evidence.toggleFavorite": "切换收藏",
        "evidence.toggleWatch": "切换关注",
        "evidence.collection.searchPrompt": "搜索全部证据",
        "evidence.collection.empty": "暂无证据",
        "evidence.collection.emptyDescription": "在证据列表里点星标或关注图标后会显示在这里。",
        "reports.searchPrompt": "搜索报告",
        "reports.noReport": "暂无报告",
        "reports.noReportDescription": "完成一次审计后会显示在这里。",
        "reports.noMatchedReport": "暂无匹配报告",
        "reports.noMatchedDescription": "调整搜索或筛选条件。",
        "reports.matchedReports": "条匹配报告",
        "reports.noSection": "未选择章节",
        "reports.noSectionDescription": "选择一个章节查看证据。",
        "reports.noEvidence": "暂无结构化证据",
        "reports.noEvidenceDescription": "切换带数量的章节，或清空当前搜索和筛选条件。",
        "reports.searchEvidence": "搜索当前章节证据",
        "reports.evidenceDetails": "证据详情",
        "reports.review": "人工复核",
        "reports.textViewer": "文本证据查看器",
        "reports.codeViewer": "代码证据查看器",
        "reports.assistantExplanation": "审计助手说明",
        "reports.attachments": "附件",
        "reports.reportProperties": "报告属性",
        "reports.metrics": "指标",
        "reports.reportFile": "报告文件",
        "reports.scanDirectory": "审计目录",
        "reports.sectionSummary": "章节摘要",
        "reports.callouts": "提示",
        "reports.evidenceCount": "证据数量",
        "reports.noEvidenceSelection": "未选择证据",
        "reports.noEvidenceSelectionDescription": "在中间列表选择一条证据后查看详情。",
        "reports.objectA": "对象 A",
        "reports.objectB": "对象 B",
        "reports.rows": "条",
        "reports.structuredRecords": "条结构化记录",
        "reports.sectionNoStructuredEvidence": "该章节暂无结构化证据。",
        "database.recovery.initFailed": "主数据库初始化失败：%@",
        "database.recovery.pending": "数据库等待恢复处理：%@",
        "database.recovery.interrupted": "上次审计运行被中断，请重新开始审计。",
        "database.recovery.title": "数据库需要恢复",
        "database.recovery.description": "主数据库无法打开，应用已暂停写入当前工作区。",
        "database.recovery.workspace": "工作区",
        "database.recovery.temporary": "临时库",
        "database.recovery.backupButton": "备份数据库",
        "database.recovery.openWorkspace": "打开工作区",
        "database.recovery.confirmTemporary": "确认临时模式",
        "database.recovery.temporaryTitle": "已进入临时数据库模式",
        "database.recovery.temporaryMessage": "本次会话写入临时目录，重启后需要重新确认或选择可写工作区。",
        "database.recovery.backupMissing": "未找到可备份数据库",
        "database.recovery.backupSucceeded": "数据库备份完成",
        "database.recovery.backupFailed": "数据库备份失败",
        "evidence.table.risk": "风险",
        "evidence.table.type": "类型",
        "evidence.table.challengeSection": "题目 / 章节",
        "evidence.table.rule": "命中规则",
        "evidence.table.openDetails": "打开证据详情",
        "evidence.table.accessibility.riskScore": "风险 %@，分数 %@",
        "evidence.table.accessibility.score": "分数 %@",
        "evidence.table.accessibility.reviewStatus": "复核状态 %@",
        "evidence.reviewSort.riskDescending": "风险优先",
        "evidence.reviewSort.scoreDescending": "分数优先",
        "evidence.reviewSort.titleAscending": "标题",
        "evidence.reviewSort.reviewStatus": "复核状态",
        "evidence.type.text": "文本",
        "evidence.type.code": "代码",
        "evidence.type.image": "图片",
        "evidence.type.metadata": "元数据",
        "evidence.type.dedup": "重复",
        "evidence.type.crossBatch": "跨批次",
        "risk.none": "未评级",
        "risk.low": "低",
        "risk.medium": "中",
        "risk.high": "高",
        "review.status.pending": "待复核",
        "review.status.confirmed": "确认违规",
        "review.status.falsePositive": "误报",
        "review.status.ignored": "忽略",
        "review.status.whitelisted": "白名单",
        "whitelist.status.clear": "未命中白名单",
        "whitelist.status.marked": "白名单降权",
        "whitelist.status.hidden": "白名单隐藏",
        "review.confirm": "确认违规",
        "review.falsePositive": "误报",
        "review.whitelist": "加入白名单",
        "review.ignore": "忽略证据",
        "review.decision": "复核结论",
        "review.severity": "风险等级",
        "review.save": "保存复核",
        "section.overview": "总览",
        "section.text": "文本",
        "section.code": "代码",
        "section.image": "图片",
        "section.metadata": "元数据",
        "section.dedup": "重复",
        "section.fingerprints": "指纹",
        "section.crossBatch": "跨批次",
        "about.menuTitle": "关于 PitcherPlant",
        "about.checkUpdates": "检查更新...",
        "about.credits": "吊椅宝宝的竞赛 WriteUP 审计工具",
        "menu.recentAudits": "最近审计",
        "menu.noAudits": "暂无审计",
        "menu.noAuditsDescription": "从主窗口开始一次审计",
        "menu.noReports": "暂无报告",
        "menu.noReportsDescription": "完成的审计会显示在这里",
        "menu.searchPrompt": "搜索审计和报告..."
    ]

    private static let english: [String: String] = [
        "app.taskMenu": "Tasks",
        "app.reportMenu": "Reports",
        "app.viewMenu": "View",
        "app.reviewMenu": "Review",
        "systemMenu.file": "File",
        "systemMenu.edit": "Edit",
        "systemMenu.view": "View",
        "systemMenu.window": "Window",
        "systemMenu.help": "Help",
        "command.showWorkspace": "Show Workspace",
        "command.startAudit": "Start Audit",
        "command.cancelAudit": "Cancel Audit",
        "command.reloadData": "Reload Data",
        "command.toggleInspector": "Show or Hide Inspector",
        "command.openReports": "Open Reports",
        "command.openLatestReport": "Open Latest Report",
        "command.showLatestInFinder": "Reveal Latest in Finder",
        "command.exportPDF": "Export Current Report as PDF",
        "command.exportHTML": "Export Current Report as HTML",
        "command.deleteReport": "Delete Current Report",
        "toolbar.reload": "Reload",
        "toolbar.start": "Start",
        "toolbar.cancel": "Cancel",
        "toolbar.settings": "Settings",
        "toolbar.showInspector": "Show Inspector",
        "toolbar.hideInspector": "Hide Inspector",
        "toolbar.toggleSidebar": "Show or Hide Sidebar",
        "toolbar.newScan": "New Scan",
        "toolbar.hideSearch": "Hide Search",
        "toolbar.titleMode.standard": "PitcherPlant",
        "toolbar.titleSelector": "Scan Mode",
        "toolbar.mode.auto": "Auto",
        "toolbar.mode.auto.subtitle": "Choose the scan strategy automatically",
        "toolbar.mode.deep": "Deep",
        "toolbar.mode.deep.subtitle": "Cover more evidence types",
        "toolbar.mode.standard": "Standard",
        "toolbar.mode.standard.subtitle": "Current default scan profile",
        "toolbar.mode.quick": "Quick",
        "toolbar.mode.quick.subtitle": "Prioritize speed and baseline checks",
        "toolbar.mode.templates": "Scan Templates",
        "toolbar.mode.template.default": "Default Template",
        "toolbar.mode.template.default.subtitle": "Full audit and report output",
        "toolbar.mode.template.review": "Evidence Review",
        "toolbar.mode.template.review.subtitle": "Prioritize manual review fields",
        "toolbar.mode.template.fast": "Fast Screening",
        "toolbar.mode.template.fast.subtitle": "Keep key risk checks",
        "toolbar.mode.temporary": "Temporary Scan",
        "sidebar.categories": "Work Navigation",
        "sidebar.evidenceCollections": "Evidence Sets",
        "sidebar.evidenceTypes": "Evidence Types",
        "sidebar.libraries": "Resources",
        "sidebar.workspace": "Workspace",
        "sidebar.allEvidence": "All Evidence",
        "sidebar.favorites": "Favorites",
        "sidebar.watched": "Watched",
        "sidebar.newAudit": "New Audit",
        "sidebar.history": "History",
        "sidebar.reports": "Reports",
        "sidebar.textEvidence": "Text",
        "sidebar.codeEvidence": "Code",
        "sidebar.imageEvidence": "Images",
        "sidebar.metadataEvidence": "Metadata",
        "sidebar.dedupEvidence": "Duplicates",
        "sidebar.crossBatchEvidence": "Cross Batch",
        "sidebar.fingerprints": "Fingerprints",
        "sidebar.whitelist": "Whitelist",
        "sidebar.settings": "Settings",
        "status.audits": "audits",
        "status.reports": "reports",
        "status.fingerprints": "fingerprints",
        "status.auditing": "Auditing...",
        "status.latest": "Latest",
        "status.ready": "Ready",
        "status.queued": "Queued",
        "status.running": "Running",
        "status.succeeded": "Completed",
        "status.failed": "Failed",
        "notice.auditCancelled": "Audit Cancelled",
        "notice.auditFailed": "Audit Failed",
        "notice.bootstrapFailed": "Bootstrap Failed",
        "notice.reloadFailed": "Reload Failed",
        "notice.deleteReportFailed": "Delete Report Failed",
        "notice.whitelistSaveFailed": "Whitelist Save Failed",
        "notice.whitelistDeleteFailed": "Whitelist Delete Failed",
        "notice.exportFailed": "Export Failed",
        "notice.exportRecordFailed": "Export Record Failed",
        "notice.exportSucceeded": "Export Complete",
        "notice.reviewSaveFailed": "Review Save Failed",
        "notice.importSucceeded": "Import Complete",
        "notice.importFailed": "Import Failed",
        "notice.retryFailed": "Retry Failed",
        "notice.fingerprintImportSucceeded": "Fingerprint Import Complete",
        "notice.fingerprintImportSucceededMessage": "Imported %d fingerprints",
        "notice.fingerprintImportSucceededWithSkippedMessage": "Imported %d fingerprints, skipped %d invalid records",
        "notice.fingerprintImportFailed": "Fingerprint Import Failed",
        "notice.fingerprintExportSucceeded": "Fingerprint Export Complete",
        "notice.fingerprintExportFailed": "Fingerprint Export Failed",
        "notice.fingerprintCleanupSucceeded": "Fingerprint Cleanup Complete",
        "notice.fingerprintCleanupSucceededMessage": "Cleaned up %d fingerprints",
        "notice.fingerprintCleanupFailed": "Fingerprint Cleanup Failed",
        "notice.importQueuedSubmissionsMessage": "%d submissions queued",
        "audit.failure.cancelled": "Audit cancelled.",
        "audit.summary.base": "Completed: %d documents / %d images / %d historical fingerprints, took %@ seconds",
        "audit.summary.recall": "%@; candidate recall %d/%d pairs, took %@ms",
        "stage.queued": "Waiting",
        "stage.initialize": "Initializing",
        "stage.scan": "Scanning files",
        "stage.parse": "Parsing documents",
        "stage.parsed": "Documents parsed",
        "stage.ocrImages": "OCR / image extraction",
        "stage.features": "Building features",
        "stage.recall": "Candidate recall",
        "stage.text": "Text analysis completed",
        "stage.code": "Code analysis completed",
        "stage.image": "Image analysis completed",
        "stage.metadata": "Metadata analysis completed",
        "stage.crossBatch": "Cross-batch matching",
        "stage.aggregate": "Risk aggregation",
        "stage.export": "Report export",
        "stage.done": "Report generated",
        "workspace.title": "Workspace",
        "workspace.recentJobs": "Recent Audits",
        "workspace.recentReports": "Recent Reports",
        "workspace.reportCenter": "Reports",
        "workspace.summary.jobs": "Audits",
        "workspace.summary.reports": "Reports",
        "workspace.summary.fingerprints": "Fingerprints",
        "workspace.summary.whitelist": "Whitelist",
        "audit.title": "New Audit",
        "audit.subtitle": "Configure paths, thresholds, OCR, and whitelist behavior",
        "audit.running": "Running",
        "audit.paths": "Paths",
        "audit.paths.subtitle": "Choose scan and report output locations",
        "audit.directory": "Audit Directory",
        "audit.outputDirectory": "Report Directory",
        "audit.fileNameTemplate": "File Name Template",
        "audit.parameters": "Detection Parameters",
        "audit.parameters.subtitle": "Control similarity, reuse, and cross-batch thresholds",
        "audit.textThreshold": "Text Threshold",
        "audit.dedupThreshold": "Duplicate Threshold",
        "audit.imageThreshold": "Image Threshold",
        "audit.simhashThreshold": "SimHash Bit Delta",
        "audit.visionOCR": "Vision OCR",
        "audit.whitelistMode": "Whitelist Mode",
        "audit.preset": "Presets",
        "audit.preset.subtitle": "Save frequently used path and threshold combinations",
        "audit.presetName": "Preset Name",
        "audit.saveCurrent": "Save Current",
        "audit.emptyPreset": "Save a preset to apply or run it directly here.",
        "audit.applyPreset": "Apply",
        "audit.runPreset": "Run",
        "audit.batchImport": "Batch Submission Import",
        "audit.batchImport.subtitle": "Supports ZIP, nested folders, and team-folder detection",
        "audit.batchImport.description": "Imported submission packages create queued audit tasks automatically.",
        "audit.importSubmissions": "Import Package",
        "mode.mark": "Mark",
        "mode.hide": "Hide",
        "history.searchPrompt": "Search task, path, or status",
        "fingerprints.searchPrompt": "Search file, author, or SimHash",
        "fingerprints.importPackage": "Import Fingerprints",
        "fingerprints.exportPackage": "Export Fingerprints",
        "fingerprints.cleanupTag": "Tag",
        "fingerprints.cleanup": "Clean Tag",
        "fingerprints.context": "Batch / Team",
        "fingerprints.tags": "Tags",
        "fingerprints.importTagsPrompt": "Import tags, comma separated",
        "fingerprints.exportTagsPrompt": "Export package tags, comma separated",
        "fingerprints.matchCount": "%d matches",
        "fingerprints.cleanupConfirmTitle": "Confirm Fingerprint Tag Cleanup",
        "fingerprints.cleanupConfirmMessage": "Tag %@ matches %d fingerprints. Cleanup removes these records from the local fingerprint library.",
        "fingerprints.empty": "Fingerprint library is empty",
        "whitelist.searchPrompt": "Search rules",
        "whitelist.type": "Type",
        "whitelist.newRule": "New Rule",
        "whitelist.rule": "Rule",
        "whitelist.save": "Save",
        "whitelist.suggestions": "Whitelist Suggestions",
        "whitelist.suggestions.failed": "Suggestion generation failed: %@",
        "whitelist.noMatchedSuggestions": "No Matching Suggestions",
        "whitelist.noMatchedSuggestionsDescription": "Refresh suggestions, then accept or ignore candidate rules.",
        "whitelist.existingRules": "Existing Rules",
        "whitelist.noMatchedRules": "No Matching Rules",
        "whitelist.noMatchedRulesDescription": "Enter a rule above and save it.",
        "whitelist.suggestionStatus": "Suggestion Status",
        "whitelist.suggestionStatus.pending": "Pending",
        "whitelist.suggestionStatus.accepted": "Accepted",
        "whitelist.suggestionStatus.dismissed": "Ignored",
        "whitelist.reason.textTemplate": "Repeated across multiple WriteUPs; suitable as a shared prompt or template snippet",
        "whitelist.reason.codeTemplate": "Structured code template appears repeatedly",
        "whitelist.reason.imageHash": "Image hash appears frequently; likely an official screenshot or shared asset",
        "whitelist.reason.metadata": "Metadata appears across multiple files and is suitable for downgrading",
        "whitelist.reason.pathPattern": "Directory names repeat and are suitable for import ignore or downgrade rules",
        "whitelist.generating": "Generating",
        "whitelist.refreshSuggestions": "Refresh Suggestions",
        "whitelist.acceptPending": "Accept Pending",
        "whitelist.pendingCount": "%d pending",
        "whitelist.author": "Author",
        "whitelist.filename": "Filename",
        "whitelist.textSnippet": "Text Snippet",
        "whitelist.codeTemplate": "Code Template",
        "whitelist.imageHash": "Image Hash",
        "whitelist.metadata": "Metadata",
        "whitelist.pathPattern": "Path Rule",
        "job.restoreParameters": "Restore Parameters",
        "job.runQueue": "Run Queue",
        "job.retry": "Retry Task",
        "job.timeline": "Timeline",
        "job.stage": "Stage",
        "job.failures": "Failures",
        "job.failedFiles": "Failed Files",
        "job.copyDiagnostics": "Copy Error Diagnostics",
        "job.noSelection": "No Task Selected",
        "job.noSelectionDescription": "Select a history item to inspect details.",
        "common.countSuffix": "items",
        "common.none": "None",
        "common.open": "Open",
        "common.refresh": "Refresh",
        "common.new": "New",
        "common.import": "Import",
        "common.quit": "Quit",
        "common.finder": "Finder",
        "common.delete": "Delete",
        "common.export": "Export",
        "common.cancel": "Cancel",
        "common.search": "Search",
        "common.file": "File",
        "common.progress": "Progress",
        "common.status": "Status",
        "common.actions": "Actions",
        "common.count": "Count",
        "common.times": "%d times",
        "common.itemCount": "%d items",
        "common.unlabeled": "Unlabeled",
        "common.samples": "Samples",
        "common.seconds": "sec",
        "common.score": "Score",
        "common.type": "Type",
        "common.badge": "Tag",
        "common.source": "Source",
        "common.summary": "Summary",
        "common.createdAt": "Created",
        "common.updatedAt": "Updated",
        "common.path": "Path",
        "common.enabled": "On",
        "common.disabled": "Off",
        "common.followSystem": "Follow System",
        "common.light": "Light",
        "common.dark": "Dark",
        "settings.title": "Settings",
        "settings.searchPrompt": "Search settings",
        "settings.general": "General",
        "settings.appearance": "Appearance",
        "settings.auditDefaults": "Audit Defaults",
        "settings.reports": "Reports",
        "settings.data": "Data",
        "settings.shortcuts": "Quick Actions",
        "settings.language": "Language",
        "settings.languageDescription": "Follow the system language or choose one manually",
        "settings.menuBar": "Menu Bar Panel",
        "settings.menuBarDescription": "Search audits and reports from the menu bar",
        "settings.workspace": "Workspace",
        "settings.workspaceDescription": "Root path used for project and data resolution",
        "settings.theme": "Appearance",
        "settings.themeDescription": "Follow system, Light, or Dark appearance",
        "settings.inspectorDefault": "Show Details on Work Pages",
        "settings.inspectorDefaultDescription": "Used for audits, history, reports, and evidence pages",
        "settings.compactRows": "Compact Rows",
        "settings.compactRowsDescription": "Use denser rows for history, reports, and libraries",
        "settings.auditDirectoryDescription": "Default folder for scanning WriteUP documents",
        "settings.reportDirectoryDescription": "Default location for reports and exported files",
        "settings.fileNameTemplateDescription": "Template used when generating report file names",
        "settings.textThresholdDescription": "Similarity threshold for text evidence",
        "settings.dedupThresholdDescription": "Threshold for duplicate content detection",
        "settings.imageThresholdDescription": "Hash distance threshold for reused images",
        "settings.simhashThresholdDescription": "Allowed SimHash bit delta for cross-batch checks",
        "settings.visionOCRDescription": "Use system Vision to recognize text in PDFs and images",
        "settings.whitelistModeDescription": "Mark or hide results that match whitelist rules",
        "settings.calibration": "Calibration",
        "settings.calibrationPreset": "Threshold Preset",
        "settings.calibrationEvaluation": "Calibration Evaluation",
        "settings.applyPreset": "Apply Preset",
        "settings.runCalibration": "Run Calibration",
        "settings.calibrationStatus": "Calibration Status",
        "settings.calibrationSummary": "Samples %d · Precision %.2f · Recall %.2f · F1 %.2f",
        "settings.calibrationDescription": "Show Precision, Recall, and F1 from calibration fixtures",
        "settings.calibrationMissingManifest": "Calibration manifest not found: Resources/Calibration/manifest.json",
        "settings.calibrationThreshold": "Threshold",
        "settings.calibrationRowAccessibility": "%@, samples %d, Precision %@, Recall %@, F1 %@",
        "settings.auditAssistant": "Audit Assistant",
        "settings.auditAssistantMode": "Assistant Mode",
        "settings.auditAssistantModeDescription": "Choose Off, local command, or external API",
        "settings.auditAssistantTimeout": "Timeout",
        "settings.auditAssistantTimeoutDescription": "Maximum wait time for local commands and external APIs",
        "settings.auditAssistantKeychain": "Keychain Reference",
        "settings.auditAssistantKeychainDescription": "External API credential reference passed as the X-PitcherPlant-Credential-Ref request header",
        "settings.auditAssistantEndpointCommand": "Endpoint / Command",
        "settings.auditAssistantLocalCommand": "Local Command",
        "settings.auditAssistantAPIEndpoint": "API Endpoint",
        "settings.auditAssistantDisabledSubtitle": "Configuration is preserved and takes effect after enabling a mode",
        "settings.auditAssistantLocalSubtitle": "Runs through zsh -lc with the evidence payload written to standard input",
        "settings.auditAssistantAPISubtitle": "Sends the evidence payload as a POST JSON request",
        "calibration.preset.conservative": "Conservative",
        "calibration.preset.conservative.subtitle": "Raise thresholds to reduce false positives",
        "calibration.preset.balanced": "Balanced",
        "calibration.preset.balanced.subtitle": "Use the current default thresholds",
        "calibration.preset.aggressive": "Aggressive",
        "calibration.preset.aggressive.subtitle": "Lower text thresholds to improve suspicious recall",
        "auditAssistant.mode.disabled": "Off",
        "auditAssistant.mode.localCommand": "Local Command",
        "auditAssistant.mode.externalAPI": "External API",
        "settings.preferInAppReports": "Open Reports In App",
        "settings.preferInAppReportsDescription": "Prefer the in-app report center for audit results",
        "settings.defaultExportFormat": "Default Export Format",
        "settings.defaultExportFormatDescription": "Default format used for current report export",
        "settings.attachmentPreview": "Attachment Previews",
        "settings.attachmentPreviewDescription": "Show thumbnails and attachment previews in report details",
        "settings.databaseLocation": "Database Location",
        "settings.databaseLocationDescription": "Path to the active SQLite database file",
        "settings.recordCounts": "Record Counts",
        "settings.recordCountsDescription": "Current record counts in the database",
        "settings.openDataDirectory": "Open Data Directory",
        "settings.reloadData": "Reload Data",
        "settings.dataActionsDescription": "Open the database folder or refresh current data",
        "settings.openReports": "Open Reports",
        "settings.openReportsDescription": "Switch to the in-app report center",
        "settings.exportHTML": "Export HTML",
        "settings.exportPDF": "Export PDF",
        "settings.exportReport": "Export Report",
        "settings.exportBundle": "Evidence Bundle ZIP",
        "settings.openFinder": "Open Finder",
        "settings.choose": "Choose",
        "settings.currentPrefix": "Current: ",
        "settings.dataActions": "Data Actions",
        "settings.quickOpen": "Quick Access",
        "settings.reportActions": "Report Actions",
        "settings.reportActionsDescription": "Export or reveal the currently selected report",
        "settings.startAuditDescription": "Start a scan with the current audit defaults",
        "reports.title": "Reports",
        "reports.subtitle": "Review sections, evidence tables, and details in the app",
        "reports.selectReport": "Select Report",
        "reports.filter": "Filter",
        "reports.evidenceFilter.all": "All",
        "reports.evidenceFilter.highRisk": "High Risk",
        "reports.evidenceFilter.attachments": "With Attachments",
        "reports.sort": "Sort",
        "reports.sort.default": "Default",
        "reports.sort.severity": "Risk First",
        "reports.sort.title": "Title",
        "evidence.addFavorite": "Add Favorite",
        "evidence.removeFavorite": "Remove Favorite",
        "evidence.addWatch": "Watch Evidence",
        "evidence.removeWatch": "Stop Watching",
        "evidence.toggleFavorite": "Toggle Favorite",
        "evidence.toggleWatch": "Toggle Watch",
        "evidence.collection.searchPrompt": "Search all evidence",
        "evidence.collection.empty": "No Evidence",
        "evidence.collection.emptyDescription": "Use the star or watch icon in an evidence row to show it here.",
        "reports.searchPrompt": "Search reports",
        "reports.noReport": "No Reports",
        "reports.noReportDescription": "Finished audits appear here.",
        "reports.noMatchedReport": "No Matching Reports",
        "reports.noMatchedDescription": "Adjust search or filters.",
        "reports.matchedReports": "matched reports",
        "reports.noSection": "No Section Selected",
        "reports.noSectionDescription": "Choose a section to view evidence.",
        "reports.noEvidence": "No Structured Evidence",
        "reports.noEvidenceDescription": "Choose a section with rows, or clear search and filters.",
        "reports.searchEvidence": "Search current section",
        "reports.evidenceDetails": "Evidence Details",
        "reports.review": "Human Review",
        "reports.textViewer": "Text Evidence Viewer",
        "reports.codeViewer": "Code Evidence Viewer",
        "reports.assistantExplanation": "Assistant Explanation",
        "reports.attachments": "Attachments",
        "reports.reportProperties": "Report Properties",
        "reports.metrics": "Metrics",
        "reports.reportFile": "Report File",
        "reports.scanDirectory": "Audit Directory",
        "reports.sectionSummary": "Section Summary",
        "reports.callouts": "Notes",
        "reports.evidenceCount": "Evidence Count",
        "reports.noEvidenceSelection": "No Evidence Selected",
        "reports.noEvidenceSelectionDescription": "Select an evidence row in the middle pane.",
        "reports.objectA": "Object A",
        "reports.objectB": "Object B",
        "reports.rows": "rows",
        "reports.structuredRecords": "structured records",
        "reports.sectionNoStructuredEvidence": "This section has no structured evidence.",
        "database.recovery.initFailed": "Main database initialization failed: %@",
        "database.recovery.pending": "Database recovery required: %@",
        "database.recovery.interrupted": "The previous audit run was interrupted. Start the audit again.",
        "database.recovery.title": "Database Recovery Required",
        "database.recovery.description": "The main database cannot be opened. Writes to the current workspace are paused.",
        "database.recovery.workspace": "Workspace",
        "database.recovery.temporary": "Temporary Store",
        "database.recovery.backupButton": "Back Up Database",
        "database.recovery.openWorkspace": "Open Workspace",
        "database.recovery.confirmTemporary": "Use Temporary Mode",
        "database.recovery.temporaryTitle": "Temporary Database Mode",
        "database.recovery.temporaryMessage": "This session writes to a temporary directory. Confirm again or choose a writable workspace after restart.",
        "database.recovery.backupMissing": "No Database to Back Up",
        "database.recovery.backupSucceeded": "Database Backup Complete",
        "database.recovery.backupFailed": "Database Backup Failed",
        "evidence.table.risk": "Risk",
        "evidence.table.type": "Type",
        "evidence.table.challengeSection": "Challenge / Section",
        "evidence.table.rule": "Matched Rule",
        "evidence.table.openDetails": "Open evidence details",
        "evidence.table.accessibility.riskScore": "Risk %@, score %@",
        "evidence.table.accessibility.score": "Score %@",
        "evidence.table.accessibility.reviewStatus": "Review status %@",
        "evidence.reviewSort.riskDescending": "Risk First",
        "evidence.reviewSort.scoreDescending": "Score First",
        "evidence.reviewSort.titleAscending": "Title",
        "evidence.reviewSort.reviewStatus": "Review Status",
        "evidence.type.text": "Text",
        "evidence.type.code": "Code",
        "evidence.type.image": "Image",
        "evidence.type.metadata": "Metadata",
        "evidence.type.dedup": "Duplicate",
        "evidence.type.crossBatch": "Cross Batch",
        "risk.none": "Unrated",
        "risk.low": "Low",
        "risk.medium": "Medium",
        "risk.high": "High",
        "review.status.pending": "Pending",
        "review.status.confirmed": "Confirmed",
        "review.status.falsePositive": "False Positive",
        "review.status.ignored": "Ignored",
        "review.status.whitelisted": "Whitelisted",
        "whitelist.status.clear": "No Whitelist Match",
        "whitelist.status.marked": "Whitelist Downgraded",
        "whitelist.status.hidden": "Whitelist Hidden",
        "review.confirm": "Confirm",
        "review.falsePositive": "False Positive",
        "review.whitelist": "Whitelist",
        "review.ignore": "Ignore Evidence",
        "review.decision": "Decision",
        "review.severity": "Risk Level",
        "review.save": "Save Review",
        "section.overview": "Overview",
        "section.text": "Text",
        "section.code": "Code",
        "section.image": "Images",
        "section.metadata": "Metadata",
        "section.dedup": "Duplicates",
        "section.fingerprints": "Fingerprints",
        "section.crossBatch": "Cross Batch",
        "about.menuTitle": "About PitcherPlant",
        "about.checkUpdates": "Check for Updates...",
        "about.credits": "D1a0y1bb's Competition WriteUP Audit Tool",
        "menu.recentAudits": "Recent Audits",
        "menu.noAudits": "No Audits",
        "menu.noAuditsDescription": "Start an audit from the main window",
        "menu.noReports": "No Reports",
        "menu.noReportsDescription": "Finished audits appear here",
        "menu.searchPrompt": "Search audits and reports...",
        "update.button.title": "Update",
        "update.button.help": "New version available",
        "update.button.accessibility": "New version available, view update"
    ]
}

extension AppState {
    func t(_ key: String) -> String {
        LocalizationStrings.text(key, language: appSettings.language)
    }

    func tf(_ key: String, _ arguments: CVarArg...) -> String {
        String(
            format: t(key),
            locale: effectiveLocale ?? .current,
            arguments: arguments
        )
    }

    func title(for item: MainSidebarItem) -> String {
        t(item.localizationKey)
    }

    func title(for scope: EvidenceCollectionScope) -> String {
        t(scope.localizationKey)
    }

    func title(for status: AuditJobStatus) -> String {
        t(status.localizationKey)
    }

    func title(for stage: AuditStage) -> String {
        t(stage.localizationKey)
    }

    func title(for mode: AuditConfiguration.WhitelistMode) -> String {
        t(mode.localizationKey)
    }

    func title(for preset: AuditCalibrationPreset) -> String {
        switch preset {
        case .conservative: return t("calibration.preset.conservative")
        case .balanced: return t("calibration.preset.balanced")
        case .aggressive: return t("calibration.preset.aggressive")
        }
    }

    func subtitle(for preset: AuditCalibrationPreset) -> String {
        switch preset {
        case .conservative: return t("calibration.preset.conservative.subtitle")
        case .balanced: return t("calibration.preset.balanced.subtitle")
        case .aggressive: return t("calibration.preset.aggressive.subtitle")
        }
    }

    func title(for mode: AuditAssistantConfiguration.Mode) -> String {
        switch mode {
        case .disabled: return t("auditAssistant.mode.disabled")
        case .localCommand: return t("auditAssistant.mode.localCommand")
        case .externalAPI: return t("auditAssistant.mode.externalAPI")
        }
    }

    func title(for type: WhitelistRule.RuleType) -> String {
        t(type.localizationKey)
    }

    func title(for filter: ReportEvidenceFilter) -> String {
        t(filter.localizationKey)
    }

    func title(for sortOrder: ReportEvidenceSortOrder) -> String {
        t(sortOrder.localizationKey)
    }

    func title(for sortOrder: EvidenceReviewTableSortOrder) -> String {
        t(sortOrder.localizationKey)
    }

    func title(for type: EvidenceType) -> String {
        switch type {
        case .text: return t("evidence.type.text")
        case .code: return t("evidence.type.code")
        case .image: return t("evidence.type.image")
        case .metadata: return t("evidence.type.metadata")
        case .dedup: return t("evidence.type.dedup")
        case .crossBatch: return t("evidence.type.crossBatch")
        }
    }

    func title(for level: RiskLevel) -> String {
        switch level {
        case .none: return t("risk.none")
        case .low: return t("risk.low")
        case .medium: return t("risk.medium")
        case .high: return t("risk.high")
        }
    }

    func title(for decision: EvidenceDecision) -> String {
        switch decision {
        case .pending: return t("review.status.pending")
        case .confirmed: return t("review.status.confirmed")
        case .falsePositive: return t("review.status.falsePositive")
        case .ignored: return t("review.status.ignored")
        case .whitelisted: return t("review.status.whitelisted")
        }
    }

    func title(for status: WhitelistEvaluation.Status) -> String {
        switch status {
        case .clear: return t("whitelist.status.clear")
        case .marked: return t("whitelist.status.marked")
        case .hidden: return t("whitelist.status.hidden")
        }
    }

    func title(for status: WhitelistSuggestionStatus) -> String {
        t(status.localizationKey)
    }

    func title(for kind: ReportSectionKind) -> String {
        switch kind {
        case .overview: return t("section.overview")
        case .text: return t("section.text")
        case .code: return t("section.code")
        case .image: return t("section.image")
        case .metadata: return t("section.metadata")
        case .dedup: return t("section.dedup")
        case .fingerprints: return t("section.fingerprints")
        case .crossBatch: return t("section.crossBatch")
        }
    }
}
